[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"
watchPatterns = [
    "Discord_Message_exporter.py",
    "requirements.txt"
]

[deploy]
startCommand = "python Discord_Message_exporter.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300
numReplicas = 1

[deploy.env]
PYTHON_VERSION = "3.11.7"
PYTHONUNBUFFERED = "1"

[service]
autoStart = true
autoDeploy = true 