[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 Discord_Message_exporter.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
PYTHON_VERSION = "3.11.7"
PYTHONUNBUFFERED = "1"

[service]
autoStart = true
autoDeploy = true 