[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python Discord_Message_exporter.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 